// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Sh2VIZz7M0W0tmPUtYnKkyuhlEAVG7E',
    appId: '1:790051385168:web:b8ad607ea34044f9454655',
    messagingSenderId: '790051385168',
    projectId: 'movie-tracker-8b562',
    authDomain: 'movie-tracker-8b562.firebaseapp.com',
    storageBucket: 'movie-tracker-8b562.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeEI52sSoGCi0Gxz4H7xp31BEOVDfmxyQ',
    appId: '1:790051385168:android:b08a2870ff1a8b91454655',
    messagingSenderId: '790051385168',
    projectId: 'movie-tracker-8b562',
    storageBucket: 'movie-tracker-8b562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl7s6TR6YutL_rNpH0FxUrEzzScTrO4lc',
    appId: '1:790051385168:ios:c1fcb52d385d87ab454655',
    messagingSenderId: '790051385168',
    projectId: 'movie-tracker-8b562',
    storageBucket: 'movie-tracker-8b562.appspot.com',
    iosBundleId: 'com.example.cinemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl7s6TR6YutL_rNpH0FxUrEzzScTrO4lc',
    appId: '1:790051385168:ios:27bf4b08adaae6fe454655',
    messagingSenderId: '790051385168',
    projectId: 'movie-tracker-8b562',
    storageBucket: 'movie-tracker-8b562.appspot.com',
    iosBundleId: 'com.example.cinemate.RunnerTests',
  );
}
